- .eslintrc
- .prettierrc
- package.json
- src/shares/header.tsx
- src/shares/login/login.tsx
- tailwind.config.ts
- yarn.lock
[Frontend-3] Create registr modal
Kucherenko Alexandr
3. Changes:
Create registr modal
4. Conclusion:
Project was built with NEXTJS build successfully.
> [Frontend-4]: Create registr modal

- src/app/layout.tsx
- src/components/Footer.tsx
Added footer component with mobile adaptive layout
> [IL-172]: Create footer

- src/app/_components/ProductCard.tsx
- src/app/_components/ProductList.tsx
- src/app/layout.tsx
- src/app/product/[id]/page.tsx
- src/app/product/_components/AddToCart.tsx
- src/app/product/_components/Counter.tsx
- src/app/product/error.tsx
- src/components/ui/Button.tsx
- src/constants/product.ts
- tailwind.config.ts
1. Create product page ( server component )
2. Create error page
3. Create reusable purple Button component
4. Move into constants productSize value ( in future will be implemented in backend api) and refactor related ProductCard
> [IL-138]: create product page

- package.json
- src/hooks/useStoreData.ts
- src/store/cartSlice.ts
- src/store/store.ts
- yarn.lock
Hook useStoreDate is used to prevent NextJs hydration error while using localStorage
> [IL-220]: Create client cart with localStorage synchronization

- package.json
- src/components/ui/Button.tsx
- src/components/ui/FormInput.tsx
- tailwind.config.ts
- yarn.lock
- Create custom input to work with react-hook-form
- Update Button component name and improve props types of Button component
- Add tailwind-merge library to work with styles
> Create custom input component

- package.json
- yarn.lock
Library to validate form fields
> Add yup library to validate forms

- src/app/cart/_components/CartElement.tsx
- src/components/ui/Counter.tsx
- src/store/cartSlice.ts
Tasks's name:
[IL-259] Disappearing cart products
Developer's full name:
Iakiv Pekarskyi
Changes:
Added additional closure to the Counter component to prevent showing zero in the counter.
Added additional closure to the removeItem function to prevent item from dissapearing from the cart.
> Dissapearing cart products

- .github/workflows/dev-branch-pr-build-and-test-pipeline.yaml
- .github/workflows/dev-branch-pr-deployment-pipeline.yml
- README.md
- START.md
- jest.config.js
- package.json
- sonar-project.properties
- yarn.lock
**1. Task's name:** 
[[IL-262]: Add SonarQube Analysis for FE DEV Pipeline](http://jira/browse/IL-262)
**2. Developer's full name:**
Anna Striganova
**3. Changes:**
- added `.github/workflows/dev-branch-pr-build-and-test-pipeline.yaml`
- `yarn jest --coverage` - runs all tests and generates coverage reports
- runs SonarQube analysis
- added test reporters to Jest config
- fixed  links to SwaggerUI in `README.md`
> [IL-262] SonarQube pipeline for FE

- .gitignore
- .vscode/settings.json
- src/app/@parallel/(.)auth/login/page.tsx
- src/app/_components/CircleAddBtn.tsx
- src/app/_components/ProductCard.tsx
- src/app/auth/registration/page.tsx
- src/app/cart/_components/CartElement.tsx
- src/app/globals.css
- src/app/layout.tsx
- src/app/product/[id]/page.tsx
- src/app/product/_components/AddToCart.tsx
- src/app/product/error.tsx
- src/app/product/layout.tsx
- src/app/profile/_components/FilledProfile/FiledProfile.tsx
- src/app/profile/_components/FormProfile/FormProfile.tsx
- src/app/profile/page.tsx
- src/components/CartButton.tsx
- src/components/Footer.tsx
- src/components/modals/AuthModal.tsx
- src/components/modals/AuthModalRegistration.tsx
- src/components/modals/forms/LoginForm.tsx
- src/components/modals/forms/RegistrationForm.tsx
- src/components/ui/Button.tsx
- src/components/ui/Calendar.tsx
- src/components/ui/Counter.tsx
- src/components/ui/FormInput.tsx
- src/components/ui/ImageUpload.tsx
- src/components/ui/ProfileListItem.tsx
- src/components/utility/Price/Price.tsx
- src/validation/userFormSchema.ts
> Refactored issues caught by SQ

- src/app/cart/_components/CartElement.tsx
- src/components/CartButton.tsx
- src/components/Footer.tsx
- src/components/Header.tsx
- src/components/HeaderHeart.tsx
- src/components/ui/Counter.tsx
1. Resize header and footer
2. Change icon color
3. Add heart button to cart
> style: resize footer + header, button color

- src/app/_components/ProductCard.tsx
- src/app/cart/_components/CartElement.tsx
- src/app/favourites/_components/FavouritesFull.tsx
- src/app/favourites/page.tsx
- src/components/Header.tsx
> fix:eslint errors

- src/app/_components/ProductCard.tsx
- src/app/_components/ProductList.tsx
- src/app/cart/_components/CartElement.tsx
- src/app/product/[id]/page.tsx
- src/models/Products.ts
- src/utils/createImgUrl.ts
> Add images

- __tests__/unit/utils/getImgUrl.test.tsx
- src/app/product/[id]/page.tsx
- src/components/Cart/CartElement/CartElement.tsx
- src/components/Favourites/FavElement/FavElement.tsx
- src/components/Product/ProductCard/ProductCard.tsx
- src/utils/createImgUrl.ts
- src/utils/getImgUrl.ts
**1. Task's name:** 
[SQ code smell] `createImgUrl` always returned null
**2. Developer's full name:**
Anna Striganova
**3. Changes:**
- renamed `createImgUrl` >> `getImgUrl`, refactored related code
- added super simple test
> SQ: refactored createImgUrl

- src/app/product/[id]/page.tsx
- src/components/Footer/Footer.tsx
- src/components/Product/AddToCard/AddToCart.tsx
- src/components/Product/ProductCard/ProductCard.tsx
- src/components/Product/ProductList/ProductList.tsx
- src/components/UI/Buttons/Button/Button.tsx
- src/components/UI/Counter/Counter.tsx
- copied work from the forked repo. 
- fixed everything that was mentioned in the previous PR
> Feature/il 296/uifix

- .gitignore
- src/components/Favourites/FavouritesEmpty/FavouritesEmpty.tsx
- src/components/Profile/FilledProfile/FiledProfile.tsx
- src/types/services/UserServices.ts
- src/validation/userFormSchema.ts
1) Make redirecting to login page after clicking 'login' button on Favorite page
2) In profile edit form remove requiring to fill unrequired fields
> Fix 2 bugs: with login btn and login inputs

- tsconfig.json
Delete dev types from tsconfig.json
> fix types in tsconfig.json

- src/components/UI/Dropdown/Dropdown.tsx
Change z-index in dropdown component
> bugfix dropdown

- src/validation/userFormSchema.ts
1. Added hyphen and space to validation schema
> [IL-327] - lastname validation

- src/components/Product/ProductCard/ProductCard.tsx
- src/components/Product/ProductList/ProductList.tsx
Display Issue: Misaligned "Add to Cart" Button on the Main Page
3. Changes:
- change rows alignment in product card
- add bottom margin in product list section
> [ISSUE-159]: Display Issue: Misaligned "Add to Cart" Button on the Main Page

- src/components/UI/Counter/Counter.tsx
1. added button tags to the counter
> [IL -331] - wrapped plus&minus with btn tag

- src/components/Product/ProductList/ProductList.tsx
- src/components/Review/ReviewsSection/ReviewsSection.tsx
- src/components/Review/ReviewsSorter/ReviewsSorter.tsx
- src/components/UI/Dropdown/Dropdown.tsx
- src/constants/productSortOptions.ts
- src/constants/reviewsSortOptions.ts
- src/hooks/useProducts.ts
- src/hooks/useReviews.ts
- src/types/Dropdown.ts
- src/types/ISortParams.ts
- src/types/ProductSortParams.ts
- src/utils/getDefaultSortOption.ts
Improve Product Sorting on Homepage
3. Changes:
add new sort options
change dropdown styles
add default sort option
> [IL-318]: Improve Product Sorting on Homepage

- src/validation/userFormSchema.ts
(PERSONAL ACCOUNT PAGE) Field First Name accept 1 symbol value on edit profile page
3. Changes:
- change validation rules for user profile form (name and last name)
> [ISSUE-134]: (PERSONAL ACCOUNT PAGE) Field First Name accept 1 symbol value on edit profile page

- package-lock.json
- src/validation/userFormSchema.ts
Modified regular expression to fix the bugs.
> [ISSUE-176] - Incomplete validation of the email

- src/components/Cart/CartElement/CartElement.tsx
- src/store/cartSlice.ts
(SHOPPING CART PAGE) Total per line price and total cart price does not change after increase/decrease items
3. Changes:
- change 'add' and 'remove' functions in cart store
- change price value in CartElement component
4. Links to issues:
- https://github.com/Sunagatov/Iced-Latte-Frontend/issues/148
- https://github.com/Sunagatov/Iced-Latte-Frontend/issues/189
> [ISSUE-148/189]: (SHOPPING CART PAGE) Total per line price and total cart price does not change after increase/decrease items

- __tests__/Home.test.tsx
- public/triangleArrowDown.svg
- public/triangleArrowUp.svg
- src/app/page.tsx
- src/components/Product/FilterSidebar/FilterCheckboxGroup.tsx
- src/components/Product/FilterSidebar/Filters.tsx
- src/components/Product/ProductList/ProductList.tsx
- src/hooks/useProducts.ts
- src/services/apiService.ts
- src/store/productFiltersStore.ts
- src/types/Products.ts
- add filtering products by seller
- add brands and sellers fetching from backend
> feat: add filtering products by seller

- src/components/Product/FilterSidebar/Filters.tsx
Fixed a typo in the product filter from the PR: https://github.com/Sunagatov/Iced-Latte-Frontend/pull/208
> fix: fix a typo in the product filter

- __tests__/Home.test.tsx
- src/components/Product/ProductWithReviews/ProductWithReviews.tsx
- src/components/Review/ReviewsSection/ReviewsSection.tsx
(PRODUCT PAGE) Statistics with ratings disappears
**Changes:**
- change product statistics display logic
- add async to Home.test
**Before:**
**After:**
> [ISSUE-197]: (PRODUCT PAGE) Statistics with ratings disappears

- src/components/Product/ProductOverview/ProductOverview.tsx
- src/components/Product/ProductRating/ProductRating.tsx
- src/components/UI/Rating/Rating.tsx
- src/types/RatingType.ts
(PRODUCT PAGE) Incorrect rating and reviews quantity display
**Changes:**
- add 'no rating' message on product page
**Links to issues:**
https://github.com/Sunagatov/Iced-Latte-Frontend/issues/198
**Before:**
**After:**
> [ISSUE-198]: (PRODUCT PAGE) Incorrect rating and reviews quantity display

- src/components/UI/Rating/Rating.tsx
**Changes:**
- Delete unnecessary 'span'
> Rating component change

- src/components/Product/FilterSidebar/Filters.tsx
- src/components/Product/FilterSidebar/FiltersGroupTitle.tsx
- src/components/Product/FilterSidebar/PriceFilter.tsx
- src/components/Product/ProductList/ProductList.tsx
- src/components/Product/ProductRatingFilter/ProductRatingFilter.tsx
- src/components/UI/FormInput/FormInput.tsx
- src/hooks/useProducts.ts
- src/store/productFiltersStore.ts
- src/types/FormInput.ts
- src/types/IProductPriceFilter.ts
- src/validation/filterProductsByPriceSchema.ts
1. Add filtering by price.
2. Add filtering by rating.
> Add filtering products by price and rating

- src/components/Product/ProductOverview/ProductOverview.tsx
- src/components/Review/ReviewsSection/ReviewsSection.tsx
(PRODUCT PAGE) Rating and reviews counter don't refresh after delete review
**Changes:**
- add reviewsStatistics to components to revalidate statistics after add/delete review
**Issue:**
https://github.com/Sunagatov/Iced-Latte-Frontend/issues/232
> [ISSUE-232]: (PRODUCT PAGE) Rating and reviews counter don't refresh after delete review

- src/app/page.tsx
- src/components/Product/ProductCard/ProductCard.tsx
- src/components/Product/ProductCatalog/ProductCatalog.tsx
- src/components/Product/ProductList/ProductList.tsx
- src/hooks/useProducts.ts
(MAIN PAGE-PRODUCT'S CATALOG) Need to fix layout when no products and when one row of products
**Changes:**
- move product list from "ProductList" into a separate component
- rename old "ProductList" component to "Product Catalog" component
- fixed layout display when there is no products
- fixed layout display when there is only 1 row of products left
- change product list styles on screens < 768px
**before:**
- one row
- 0 products
- 767px screen
**after:**
- one row
- 0 products
- 767px screen
> [ISSUE-226]: (MAIN PAGE-PRODUCT'S CATALOG) Need to fix layout when no products and when one row of products

- src/components/Footer/Footer.tsx
**Changes:**
fix footer layout on screens < 768px
**before:**
**after:**
> fix: change footer styles

- src/components/Product/ProductRating/ProductRating.tsx
- src/components/UI/Buttons/CircleAddBtn/CircleAddBtn.tsx
> fix: change product card styles

- src/components/Review/ReviewRatingFilter/ReviewRatingFilter.tsx
- src/components/UI/Rating/Rating.tsx
- src/types/RatingType.ts
Task's name:
(PRODUCT PAGE) А dot as a decimal separator in the product rating (filter) #233
Developer name:
Akhil k
Changes:
Wrap avgRating in the Rating component.
Issue:
https://github.com/Sunagatov/Iced-Latte-Frontend/issues/233
> [ISSUE-233]: (PRODUCT PAGE) А dot as a decimal separator in the product rating (filter)

- src/components/Cart/CartElement/CartElement.tsx
(SHOPPING CART) Brand and seller names, Product price for the 1 product item, redesign
**Changes:**
- product cart item redesign
- add brand and seller names
**Before:**
**After:**
> [ISSUE-246]: (SHOPPING CART) Brand and seller names, Product price for the 1 product item, redesign

- src/components/Review/Review/Review.tsx
Task's name:
(PRODUCT PAGE) The "See more" button does not work for reviews with 301 or more characters
https://github.com/Sunagatov/Iced-Latte-Frontend/issues/231
Developer name:
Akhil k
Changes:
Removed expansion props and integrated them directly into the review component to prevent unnecessary re-renders.
Issue:
https://github.com/Sunagatov/Iced-Latte-Frontend/issues/231
> [ISSUE-231]: (PRODUCT PAGE) The "See more" button does not work for reviews with 301 or more characters

- __tests__/Home.test.tsx
- src/components/Product/FilterSidebar/MobileFilterSidebar.tsx
- src/components/Product/ProductCatalog/ProductCatalog.tsx
https://github.com/Sunagatov/Iced-Latte-Frontend/issues/243
When you scroll the main page down, filters sections are  pinned to the top of the screen and are always visible.
> IL-352 - [FE] Add scroll to filter bars
